name: Publish Codespace Base Image

on:
  push:
    branches:
      - workspace-git
  workflow_dispatch:

jobs:
  publish-code-space-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Codespace Base Image
      run: |
        docker-compose -f .devcontainer/docker-compose.yml build base
        docker tag base:latest ghcr.io/chrisk8er/chatwoot_codespace:workspace-git
        docker push ghcr.io/chrisk8er/chatwoot_codespace:workspace-git